name: Build and Deploy

on:
  push:
    branches:
      - 'master'  # Replace 'main' with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3
      - name: Build Docker image
        working-directory: .
        run: docker build -f Dockerfile -t satoru429/reactapp:latest .
        # Replace 'my-docker-image' with your desired image name

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Replace 'DOCKER_USERNAME' and 'DOCKER_PASSWORD' with your Docker Hub credentials set as secrets

      - name: Push Docker image to Docker Hub
        run: docker push satoru429/reactapp:latest
        # Replace 'my-docker-image' with your desired image name
        

      - name: Azure Web app Development
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'reactappsvk'
          publish_profile: ${{ secrets.REACT_PP }}
          images: 'satoru429/reactapp:latest'
